### ISSUE TITLE
is there any docs about network protocol for relays cardano

### ISSUE THREAD

**Issue by ocoderr** [luoqeng/adalite-go#1]
I am looking for how to send the signed transaction data to the cardano node.It seems that this warehouse is what I am looking for. The problem is that I don't understand, there are a lot of hard-coded numbers。

Is there any documentation explaining why you should do this?

**Comment by luoqeng** [comment]
The node does not provide broadcast RPC. The implementation is a direct docking node broadcast protocol. The serialization of the communication protocol is not implemented, but is implemented according to packet capture.

Reference: https://github.com/vacuumlabs/adalite/blob/ea39d44b42b0a14e82e13cde4dbd2ffae21c16c6/server/transactionSubmitter.js

Related to the protocol is a magic number that can be found in the official configuration.
protocolMagic : 764824073 HEX 2d964a09
https://raw.githubusercontent.com/input-output-hk/cardano-sl/develop/lib/mainnet-genesis.json
